name: Deploy to EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy and Restart Gunicorn
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Code to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST_DNS: ${{ secrets.HOST_DNS }}
          USERNAME: ${{ secrets.USERNAME }}
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
        run: |
          echo "${EC2_SSH_KEY}" > private_key.pem
          chmod 600 private_key.pem
          # Clean the target directory on the EC2 instance
          ssh -o StrictHostKeyChecking=no -i private_key.pem "${USERNAME}@${HOST_DNS}" "
            rm -rf ${TARGET_DIR}/* &&
            mkdir -p ${TARGET_DIR}
          "
          # Copy code to EC2 instance
          scp -o StrictHostKeyChecking=no -i private_key.pem -r ./* "${USERNAME}@${HOST_DNS}:${TARGET_DIR}"
          # SSH into EC2 and restart Gunicorn
          ssh -o StrictHostKeyChecking=no -i private_key.pem "${USERNAME}@${HOST_DNS}" "
            cd ${TARGET_DIR} &&
            sudo systemctl restart gunicorn
          "
          rm private_key.pem
